### ISSUE TITLE
daemon scheduling type support

### ISSUE THREAD

**Issue by TakatoshiMaeda** [eagletmt/hako#52]
AWS has released daemon scheduling to ECS.
https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-ecs-adds-daemon-scheduling/

Are you planning to support the daemon scheduling type?

I have a patch, but I do not know whether this change is correct or not.
https://github.com/TakatoshiMaeda/hako/commit/2030406664266e2c3220137fb2dff10562c5c09a

If the change policy is correct, I will make a pull request so please say.

thanks.

**Comment by eagletmt** [comment]
I don't have plans for daemon scheduling, but pull-requests are welcome. Your commit looks good.

**Comment by TakatoshiMaeda** [comment]
thanks. 
I made a pull request. please review.

**Comment by eagletmt** [comment]
already released in v2.2.0
