### ISSUE TITLE
Is it oposite condition?

### ISSUE THREAD

**Issue by mocyuto** [eagletmt/hako#89]
This condition represent config doesn't have `load_balancer_name` key, so I think it would be oposite condition.

`if !load_balancer_given?` 
https://github.com/eagletmt/hako/blob/master/lib/hako/schedulers/ecs_elb_v2.rb#L54

And also it is the same pattern at target group section 
https://github.com/eagletmt/hako/blob/master/lib/hako/schedulers/ecs_elb_v2.rb#L81

**Comment by eagletmt** [comment]
So... what is your suggested change that you think is correct? I'd like to hear explanation like "with this Jsonnet file, I expect XXX, but actually got YYY".

My intended behavior is also expressed in the example file in #80 .
